Simplify MNIST and NLO challenge via AWS Open Data: Main Branch
aws-samples/sagemaker-101-workshop pull request #19
Opened 2021-11-22 15:18 UTC by rosalieandico

*Issue #, if available:*
Simplify MNIST and NLO challenge via AWS Open Data
*Description of changes:*
Updated NLP/MNIST exercises.

- local_dir
- decoupled upload to S3 for simplicity and provided description - workshop feedback
- utilized --exclude and --include aws s3 sync options for better file/object management
- re-arranged role,session, bucket assignment immediately before use
- removed util.nb - not needed
- modified util.preprocessing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-25 02:02 UTC, athewsey requested changes
A few asks to tidy up - I think you'll see the same errors I did if you shut down your studio TensorFlow app, delete all local temporary `data`/`news` folders, maybe consider deleting the corresponding S3 prefixes too, and then try to run through the nbs in order?

2021-11-29 07:37 UTC, rosalieandico commented on custom_tensorflow_keras_nlp/Headline Classifier Local.ipynb
>      "%autoreload 2\n",
Done.

2021-11-29 07:37 UTC, rosalieandico commented on custom_tensorflow_keras_nlp/Headline Classifier Local.ipynb
> +    "!tar zxf {local_dir}/ag_news_csv.tgz -C {local_dir}/ --strip-components=1 --no-same-owner"
Done.

2021-11-29 07:37 UTC, rosalieandico commented on custom_tensorflow_keras_nlp/Headline Classifier Local.ipynb
> -    "import util.preprocessing\n",
Done.

2021-11-29 07:38 UTC, rosalieandico commented on custom_tensorflow_keras_nlp/Headline Classifier Local.ipynb
> +    "local_dir = \"news\"\n",
Done.

2021-11-29 07:38 UTC, rosalieandico commented on custom_tensorflow_keras_nlp/Headline Classifier SageMaker.ipynb
> +    "embedding_matrix = util.preprocessing.get_word_embeddings(tokenizer, f\"{local_dir}/embeddings\")\n"
Done.

2021-11-29 13:23 UTC, athewsey approved these changes

2021-11-29 13:28 UTC, merged